# Generated by Django 5.0.6 on 2024-07-05 23:11

import django.db.models.deletion
import eclipse_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(max_length=255, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='distros/', validators=[eclipse_app.models.validate_square_image], verbose_name='Изображение')),
                ('official_website', models.URLField(verbose_name='Официальный сайт')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('based_on', models.CharField(max_length=100, verbose_name='Основа для данной ОС')),
                ('history', models.TextField(verbose_name='История создания')),
                ('features', models.TextField(verbose_name='Особенности')),
            ],
            options={
                'verbose_name': 'Дистрибутив Linux',
                'verbose_name_plural': 'Дистрибутивы Linux',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='InstallationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='Номер шага')),
                ('step_text', models.TextField(verbose_name='Текст шага')),
                ('step_image', models.ImageField(upload_to='installation_steps/', verbose_name='Изображение шага')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_steps', to='eclipse_app.linuxdistribution', verbose_name='Дистрибутив')),
            ],
            options={
                'verbose_name': 'Шаг установки',
                'verbose_name_plural': 'Шаги установки',
            },
        ),
        migrations.CreateModel(
            name='CurrentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='Версия')),
                ('current_version', models.CharField(max_length=50, verbose_name='Текущая версия')),
                ('code_name', models.CharField(max_length=128, verbose_name='Кодовое имя')),
                ('architectures', models.PositiveIntegerField(verbose_name='Количество поддерживаемых архитектур')),
                ('packages', models.PositiveIntegerField(verbose_name='Количество пакетов')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('support_end_date', models.DateField(verbose_name='Дата окончания поддержки')),
                ('full_support_end_date', models.DateField(verbose_name='Дата окончания длительной поддержки')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_versions', to='eclipse_app.linuxdistribution', verbose_name='Дистрибутив')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
        migrations.AddField(
            model_name='linuxdistribution',
            name='tags',
            field=models.ManyToManyField(related_name='distributions', to='eclipse_app.tag', verbose_name='Теги'),
        ),
    ]
