# Generated by Django 5.0.6 on 2024-09-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0002_alter_installationstep_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentversion',
            name='architectures',
            field=models.CharField(max_length=55, verbose_name='Количество поддерживаемых архитектур'),
        ),
        migrations.AlterField(
            model_name='currentversion',
            name='full_support_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания длительной поддержки'),
        ),
        migrations.AlterField(
            model_name='currentversion',
            name='packages',
            field=models.CharField(max_length=55, verbose_name='Количество пакетов'),
        ),
        migrations.AlterField(
            model_name='currentversion',
            name='support_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания поддержки'),
        ),
    ]
