# Generated by Django 5.0.6 on 2024-09-20 20:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0003_alter_currentversion_architectures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документации')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент документации')),
            ],
        ),
    ]
