# Generated by Django 5.0.6 on 2024-09-20 20:54

import ckeditor.fields
import eclipse_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0004_documentation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentation',
            options={'verbose_name': 'Документация', 'verbose_name_plural': 'Документация'},
        ),
        migrations.AddField(
            model_name='documentation',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=eclipse_app.models.documentation_image_upload_path, verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент документации'),
        ),
        migrations.AlterField(
            model_name='installationstep',
            name='step_image',
            field=models.ImageField(blank=True, upload_to=eclipse_app.models.distro_step_upload_path, verbose_name='Изображение шага'),
        ),
        migrations.AlterField(
            model_name='linuxdistribution',
            name='image',
            field=models.ImageField(upload_to=eclipse_app.models.distro_image_upload_path, validators=[eclipse_app.models.validate_square_image], verbose_name='Изображение'),
        ),
        migrations.AlterUniqueTogether(
            name='documentation',
            unique_together={('title', 'content')},
        ),
    ]
