# Generated by Django 5.0.6 on 2024-09-20 21:10

import eclipse_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0005_alter_documentation_options_documentation_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='author',
            field=models.CharField(default='Нет', max_length=255, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='image',
            field=models.ImageField(default='/', upload_to=eclipse_app.models.documentation_image_upload_path, validators=[eclipse_app.models.validate_square_image]),
        ),
        migrations.AddField(
            model_name='documentation',
            name='pdf_only',
            field=models.BooleanField(default=False, verbose_name='True = Только в PDF'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=eclipse_app.models.documentation_pdf_upload_path, verbose_name='PDF'),
        ),
    ]
