# Generated by Django 5.0.6 on 2024-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0006_documentation_author_documentation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='topic',
            field=models.CharField(blank=True, default='Нет', max_length=255, null=True, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='year',
            field=models.CharField(blank=True, default='2001', max_length=16, null=True, verbose_name='Год выпуска'),
        ),
    ]
