# Generated by Django 5.0.6 on 2024-09-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0009_alter_article_created_at_alter_article_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
