# Generated by Django 5.0.6 on 2024-09-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0010_remove_profile_email_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='changed',
            field=models.BooleanField(default=False, verbose_name='Изменен'),
        ),
    ]
