# Generated by Django 5.0.6 on 2024-09-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0011_profile_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='changed',
            field=models.BooleanField(default=False, verbose_name='Потдтверждаю изменения'),
        ),
    ]
