# Generated by Django 5.0.6 on 2024-09-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0015_articletag_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='', max_length=255, verbose_name='Описание'),
        ),
    ]
