# Generated by Django 5.0.6 on 2024-09-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0016_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
