# Generated by Django 5.0.6 on 2024-09-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0017_remove_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=' ', max_length=255, verbose_name='Описание'),
        ),
    ]
