# Generated by Django 5.0.6 on 2024-09-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0018_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
