# Generated by Django 5.0.6 on 2024-09-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0019_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Описание'),
        ),
    ]
