# Generated by Django 5.0.6 on 2024-09-28 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0029_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(255, message='Текст должен содержать как минимум 255 символов.')], verbose_name='Описание'),
        ),
    ]
