# Generated by Django 5.0.6 on 2024-09-28 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0030_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(200, message='Кол-во символов: min:200-max:255')], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Название статьи'),
        ),
    ]
