# Generated by Django 5.0.6 on 2024-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse_app', '0031_alter_article_description_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='verification',
            field=models.BooleanField(default=False, verbose_name='Верификация'),
        ),
    ]
